version: 2.1

executors:
  node-active:
    docker:
      - image: cimg/node:18.19.0

jobs:
  pr:
    executor: node-active
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm ci
      - run: npm test
      - store_test_results:
          path: testResults

workflows:
  version: 2
  pr:
    jobs:
      - pr:
          filters:
            branches:
              ignore: master